# Generated by Django 5.1.12 on 2026-09-09 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plm', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='aliases',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='category',
            name='catalog_version',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AddField(
            model_name='category',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='category',
            name='is_selectable',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='category',
            name='parent_code',
            field=models.CharField(blank=True, max_length=2),
        ),
        migrations.AddField(
            model_name='category',
            name='parent_name',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='category',
            name='part_nature',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AddField(
            model_name='category',
            name='sort_order',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='category',
            name='standard_references',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='category',
            name='attribute_group',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
