# Generated by Django 5.1.12 on 2026-09-09 07:56

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BOM',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('bom_code', models.CharField(max_length=64, unique=True)),
                ('bom_type', models.CharField(default='EBOM', max_length=8)),
                ('name', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ExportJob',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('kind', models.CharField(max_length=32)),
                ('format', models.CharField(default='csv', max_length=16)),
                ('status', models.CharField(default='queued', max_length=20)),
                ('object_key', models.CharField(blank=True, max_length=512)),
                ('filters', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='NumberSource',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=120)),
                ('url', models.URLField(unique=True)),
                ('is_enabled', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=32, unique=True)),
                ('name', models.CharField(max_length=64)),
                ('dimension', models.CharField(default='each', max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='UploadSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('object_key', models.CharField(max_length=512, unique=True)),
                ('bucket', models.CharField(max_length=128)),
                ('filename', models.CharField(max_length=255)),
                ('content_type', models.CharField(blank=True, max_length=255)),
                ('size', models.BigIntegerField()),
                ('total_chunks', models.PositiveIntegerField(default=1)),
                ('declared_sha256', models.CharField(blank=True, max_length=64)),
                ('state', models.CharField(choices=[('created', 'Created'), ('uploaded', 'Uploaded'), ('verified', 'Verified'), ('failed', 'Failed'), ('expired', 'Expired')], default='created', max_length=20)),
                ('upload_id', models.CharField(blank=True, max_length=255)),
                ('expires_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('major_code', models.CharField(max_length=2)),
                ('minor_code', models.CharField(max_length=2)),
                ('name', models.CharField(max_length=120)),
                ('major_name', models.CharField(blank=True, max_length=120)),
                ('path', models.CharField(blank=True, max_length=255)),
                ('attribute_group', models.CharField(blank=True, max_length=120)),
                ('is_enabled', models.BooleanField(default=True)),
                ('is_leaf', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['major_code', 'minor_code'],
                'constraints': [models.UniqueConstraint(fields=('major_code', 'minor_code'), name='uniq_category_code')],
            },
        ),
        migrations.CreateModel(
            name='NumberRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('source_request_id', models.CharField(max_length=150)),
                ('operation_key', models.CharField(max_length=150, unique=True)),
                ('returned_part_code', models.CharField(blank=True, max_length=32)),
                ('status', models.CharField(default='draft', max_length=20)),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='plm.numbersource')),
            ],
        ),
        migrations.CreateModel(
            name='Part',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tenant_id', models.CharField(default='default', max_length=64)),
                ('part_code', models.CharField(max_length=32, unique=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('pending_review', 'Pending review'), ('approved', 'Approved'), ('released', 'Released'), ('obsolete', 'Obsolete')], default='draft', max_length=20)),
                ('row_version', models.PositiveIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='parts', to='plm.category')),
                ('number_request', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='plm.numberrequest')),
            ],
            options={
                'ordering': ['part_code'],
            },
        ),
        migrations.CreateModel(
            name='PartRevision',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('revision', models.CharField(default='A', max_length=8)),
                ('revision_seq', models.PositiveIntegerField(default=1)),
                ('name', models.CharField(max_length=200)),
                ('kind', models.CharField(default='standard', max_length=32)),
                ('business_lifecycle', models.CharField(default='active', max_length=20)),
                ('standard_code', models.CharField(blank=True, max_length=64)),
                ('material', models.CharField(blank=True, max_length=128)),
                ('manufacturer', models.CharField(blank=True, max_length=128)),
                ('manufacturer_part_number', models.CharField(blank=True, max_length=128)),
                ('is_customized', models.BooleanField(default=False)),
                ('rohs_standard', models.CharField(blank=True, max_length=128)),
                ('description', models.TextField(blank=True)),
                ('revision_state', models.CharField(default='draft', max_length=20)),
                ('row_version', models.PositiveIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('part', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='revisions', to='plm.part')),
                ('unit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='plm.unit')),
            ],
            options={
                'ordering': ['part', 'revision_seq'],
            },
        ),
        migrations.CreateModel(
            name='BOMRevision',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('revision', models.CharField(default='A', max_length=8)),
                ('revision_state', models.CharField(default='draft', max_length=20)),
                ('bom', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='revisions', to='plm.bom')),
                ('root_part_revision', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='plm.partrevision')),
            ],
        ),
        migrations.CreateModel(
            name='BOMItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('line_no', models.PositiveIntegerField()),
                ('quantity', models.DecimalField(decimal_places=6, max_digits=18)),
                ('position', models.CharField(default='__NO_POSITION__', max_length=128)),
                ('bom_revision', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='items', to='plm.bomrevision')),
                ('child_part_revision', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='plm.partrevision')),
                ('unit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='plm.unit')),
            ],
        ),
        migrations.CreateModel(
            name='ImportJob',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('kind', models.CharField(choices=[('category', 'category'), ('part', 'part'), ('bom', 'bom')], max_length=32)),
                ('status', models.CharField(default='queued', max_length=20)),
                ('summary', models.JSONField(blank=True, default=dict)),
                ('error_report_key', models.CharField(blank=True, max_length=512)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('upload_session', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='plm.uploadsession')),
            ],
        ),
        migrations.AddConstraint(
            model_name='partrevision',
            constraint=models.UniqueConstraint(fields=('part', 'revision'), name='unique_part_revision'),
        ),
        migrations.AddConstraint(
            model_name='bomitem',
            constraint=models.UniqueConstraint(fields=('bom_revision', 'line_no'), name='uniq_bom_line'),
        ),
    ]
